[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../shared"}
x86_64 = "0.14.9"
bit_field = "0.10.1"
derive-new = "0.5.9"
heapless = "0.7.13"